//! Regen guard for the committed `docs/openapi-extensions.json` artifact.
//!
//! The document is generated from the annotated handlers/types, so the checked-in
//! file must never drift. Regenerate it after an intentional change with:
//!
//!   UPDATE_OPENAPI=1 cargo test -p component-mgr --test openapi_current
//!
//! The plain test run asserts byte-equality with the committed file.

use std::path::PathBuf;

/// Repo-root `docs/openapi-extensions.json` — `crates/component-mgr/../../docs`.
fn artifact_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../docs/openapi-extensions.json")
}

const REGEN_HINT: &str =
    "regenerate with `UPDATE_OPENAPI=1 cargo test -p component-mgr --test openapi_current`";

#[test]
fn committed_openapi_is_current() {
    let generated = component_mgr::sovd::openapi::openapi_json_pretty();
    let path = artifact_path();

    if std::env::var_os("UPDATE_OPENAPI").is_some() {
        std::fs::write(&path, &generated).expect("write openapi artifact");
        eprintln!("wrote {}", path.display());
        return;
    }

    // The generated document is OpenAPI 3.1.
    let parsed: serde_json::Value = serde_json::from_str(&generated).unwrap();
    let version = parsed["openapi"].as_str().unwrap_or_default();
    assert!(
        version.starts_with("3.1"),
        "generated document must be OpenAPI 3.1, got {version:?}"
    );

    let committed = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("cannot read {} ({e}); {REGEN_HINT}", path.display()));
    if generated != committed {
        panic!(
            "docs/openapi-extensions.json is stale ({} generated bytes vs {} committed); {REGEN_HINT}",
            generated.len(),
            committed.len()
        );
    }
}
