[workspace]
resolver = "2"
members = [
    "crates/nv-store",
    "crates/boot",
    "crates/vm-mgr",
    "crates/host-os-mgr",
    "crates/app-mgr",
    "crates/machine-mgr",
    "crates/vm-service",
    "crates/hsm",
    "crates/sumo-dev-mint",
    "crates/sumo-verify",
    "crates/policy-eval",
    "crates/policy-partition",
    "crates/policy-build",
    "crates/ca-bundle-build",
    "crates/vhsm-ssd",
    "crates/vm-wire",
    "crates/vm-devices",
    "crates/secstore",
    "crates/component-factory",
    "crates/host-metrics",
    "crates/log-rotate",
    "crates/puller",
    "crates/hsm-rustls",
    "crates/vhsm-proto",
    "crates/vhsm-client",
]
